/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_silicongo_george_emmc_utils_MmcUtils */

#ifndef _Included_com_silicongo_george_emmc_utils_MmcUtils
#define _Included_com_silicongo_george_emmc_utils_MmcUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_silicongo_george_emmc_utils_MmcUtils
 * Method:    getMMCBlockPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_silicongo_george_emmc_1utils_MmcUtils_getMMCBlockPath
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
