/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_silicongo_george_emmc_utils_FileOperation */

#ifndef _Included_com_silicongo_george_emmc_utils_FileOperation
#define _Included_com_silicongo_george_emmc_utils_FileOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_silicongo_george_emmc_utils_FileOperation
 * Method:    is_support_direct_io
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jstring JNICALL Java_com_silicongo_george_emmc_1utils_FileOperation_is_1support_1direct_1io
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_silicongo_george_emmc_utils_FileOperation
 * Method:    rw_file
 * Signature: (Ljava/lang/String;III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_silicongo_george_emmc_1utils_FileOperation_rw_1file
  (JNIEnv *, jclass, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
